spring:
  application:
    name: api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/coupon_example
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: df159357




