spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/fastsns
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: df159357
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate


