version: "1"
services:
  db:
    image: mysql:8.0.33
    restart: always
    command:
      - --lower_case_table_names=1
      # 인코딩 설정
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    container_name: delivery-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=delivery
      - MYSQL_ROOT_PASSWORD=!df159357
      - TZ-Asia/Seoul
    volumes:
      - /Users/rookedsysc/Documents/Mysql/delivery-mysql