spring:
  jpa:
    # ???? ?? log ???
    show-sql: true
    properties:
      format_sql: true
      # ???? MySQL ??? ??? ???
      # MySQL8 << ????? class?? ???? ???? import? ? + class name?? ??
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:mysql://localhost:3306/user?userSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: "!Qhdkscjfwj12#$"